### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/password#1]
Component
- [x] Current left padding for input is 16px, Figma file is 12px, confirm with designers which one is correct
<img width="120" alt="Screen Shot 2020-02-21 at 11 26 52 AM" src="https://user-images.githubusercontent.com/10554673/74998847-312f3f00-549d-11ea-9699-4786c91f04b6.png">

- [x] Right padding of input field is 40px and Figma is 44px, also the icon should be aligned following Figma design
<img width="353" alt="Screen Shot 2020-02-21 at 11 31 23 AM" src="https://user-images.githubusercontent.com/10554673/74999166-2f19b000-549e-11ea-8c9e-2df566a1a40c.png">
<img width="162" alt="Screen Shot 2020-02-21 at 11 33 06 AM" src="https://user-images.githubusercontent.com/10554673/74999192-45c00700-549e-11ea-9c14-9f0bb11e6e6d.png">

Stories
- [x] Add Knob for custom `className` in Dynamic props

Theme
- [x] `Hover Text Color` is not working
- [x] `Active Text Color` is not working
- [x] `Disabled Text Color` is not working

**Comment by claudio-moya** [comment]
webpack
- [ ] Set `PasswordLabel` as main component, follow this one as guideline
https://github.com/rakuten-rex/text-field/blob/fb21dddb390b12cff08df2e9bcbbb65fd5e98334/.storybook/config.js#L22-L27

**Comment by Kosukeee** [comment]
> Theme
> 
> * [ ]  `Hover Text Color` is not working
> * [ ]  `Active Text Color` is not working
> * [ ]  `Disabled Text Color` is not working

PasswordUi is uncontrolled component.
`hover` and `active` state are controlled by wrapper components like `PasswordLabel`, `PasswordHelper` and `PasswordLabelHelper`.

**Comment by claudio-moya** [comment]
Component
- [ ] Password field size is not matching Figma, width 100% it's OK, height should be 40px (current 44px)
<img width="483" alt="Screen Shot 2020-02-25 at 11 56 08 AM" src="https://user-images.githubusercontent.com/10554673/75210933-d7dd4d80-57c5-11ea-853d-180e048bfd63.png">

![image](https://user-images.githubusercontent.com/10554673/75210983-fcd1c080-57c5-11ea-8b53-8eff7894fa54.png)

- [ ] Set original SVG icon size as 14x10 as in Figma file (current one is 16x16 px), verify on rex-icons if is like that, otherwise download the icon and compress it
- [ ] Position of the icon must be based on `rem` instead of percentage or line-height due to the position is related to the main div wrapper

<img width="119" alt="Screen Shot 2020-02-25 at 11 52 21 AM" src="https://user-images.githubusercontent.com/10554673/75210760-54236100-57c5-11ea-9def-28ae75abb663.png">

```css
.rex-password-ui span {
    position: absolute;
    top: 50%; // Use `rem` instead
    transform: translateY(calc(-50% + 1px)); // Don't use this for position or set size
    right: .75rem; // Check this value,  in Figma is 13px instead of 12px
    line-height: 1; // Don't use it for position
    height: 1rem; // Size is 14x10 px, use both width and height to define the SVG container 
    cursor: pointer;
}
```
